### ISSUE TITLE
请问如果希望适配别的主题的风格，在哪里改CSS样式呢？

### ISSUE THREAD

**Issue by frostime** [svchord/siyuan-arco-calendar#1]
您好，谢谢您的这个日历部件，感觉比 savor 主题的那个日历好用很多。

本人尝试把这个日历部件替换到自己常用的主题下，虽然可以用，但是和主题的画风不太一致有点别扭。
calander 目录里的 css  巨长，也看不出哪里可以更改。请问如果是希望更改一下背景颜色，让日历不至于和主题颜色差异过大，可以怎么修改呢？【只对最基本的前端有点了解，还请见谅】

![image](https://user-images.githubusercontent.com/27268127/222204284-f22876a2-611a-421a-8a1e-eb3cabf12eed.png)

**Comment by svchord** [comment]
将以下代码插入 `index.html` 的 `<head>` 标签内,并自行修改颜色

```html
<style>
// 明亮模式的颜色即删除下行内的"[arco-theme='dark']"
body[arco-theme='dark'] {
    // 页面底色
    --color-bg-1: #21252b !important;
    // 下拉选择框输入时底色
    --color-bg-2: #21252b !important;
    // 下拉选择框底色 && 下拉菜单选项悬浮底色
    --color-fill-2: #323842 !important;
    --color-fill-3: #323842 !important;

    // 日历底色
    --color-bg-popup: #282c34 !important;
    // 非当月日期，有日记底色（r,g,b）
    --gray-1: 33, 37, 43 !important;
    // 当月日期，有日记底色（r,g,b,a）
    --arcoblue-1: 60, 126, 255, 0.2 !important;
}
</style>
```

**Comment by frostime** [comment]
谢谢，有效。

![image](https://user-images.githubusercontent.com/27268127/223422366-991e3aed-c675-40f9-a3e4-87f901d94a29.png)
