### ISSUE TITLE
不兼容docker部署的思源

### ISSUE THREAD

**Issue by kokojacket** [svchord/siyuan-arco-calendar#14]
求支持docker部署的思源

**Comment by nballen-tx** [comment]
应用商店的版本还不支持，请问要怎么获得这个修复的版本呢

**Comment by svchord** [comment]
刚推上去，等集市更新吧

**Comment by lentikr** [comment]
> 刚推上去，等集市更新吧

在Linux系统docker中的使用仍然有些问题
- 日记模板路径分隔符错误
- 如果本机安装了思源，点击对应日期后似乎siyuan协议会视图唤醒本机的思源
![image](https://github.com/svchord/siyuan-arco-calendar/assets/95539012/27efa395-75e4-40b1-8435-47ed8df25239)
