### ISSUE TITLE
已有的日记不知道为何无法识别，点击日历会重新新建该日的日记

### ISSUE THREAD

**Issue by netdog2019** [svchord/siyuan-arco-calendar#16]
已有的日记不知道为何无法识别，点击日历会重新新建该日的日记，并覆盖掉原来的日记。
当前版本 v2.9.9
如果我完全重新建一个空间，日历插件是正常的。但我原有的空间里记了快2年的daily note了。

![image](https://github.com/svchord/siyuan-arco-calendar/assets/49815951/426ea465-285f-45cd-afa7-f3ba29a57be6)

**Comment by svchord** [comment]
插件是否是最新版？按理说最新版应该不会有这个问题啊

**Comment by netdog2019** [comment]
> 插件是否是最新版？按理说最新版应该不会有这个问题啊

是最新版的。1.0.5
![image](https://github.com/svchord/siyuan-arco-calendar/assets/49815951/95b6937b-fb50-49f8-b91b-7259befb8cde)

**Comment by svchord** [comment]
那试试在设置里提高搜索结果显示数，默认应该是64，提高后看看有没有作用

**Comment by netdog2019** [comment]
> 那试试在设置里提高搜索结果显示数，默认应该是64，提高后看看有没有作用

我设置成1000，可以了。3Q~~~，好像也要把目录设置成默认的才行。修改了这两点以后，插件正常了，感谢大佬的耐心指导~~~

**Comment by svchord** [comment]
目录默认是指什么意思啊

**Comment by netdog2019** [comment]
> 目录默认是指什么意思啊

新建日记的存放路径。好像必须修改成默认的/daily note/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}才可以。
我用/{{now | date "2006/01"}}/{{now | date "2006-01-02"}}就不行。我总觉得主目录也是daily note，下一级目录又来个daily note有点多了，所以就删除了一个daily note，对应的日记也都挪到上一级目录了。

**Comment by svchord** [comment]
下个版本就可以支持自定义的了

**Comment by netdog2019** [comment]
> 下个版本就可以支持自定义的了

赞~~~

**Comment by HowcanoeWang** [comment]
> 那试试在设置里提高搜索结果显示数，默认应该是64，提高后看看有没有作用

感觉还是应该把插件的逻辑修改成每次都搜索当前月份的，这样默认的64绝对是够用的，修改最大搜索数会影响整体思源笔记的搜索性能

**Comment by svchord** [comment]
新版已解决
