### ISSUE TITLE
切换笔记本后，日历部件会自动退出

### ISSUE THREAD

**Issue by frostime** [svchord/siyuan-arco-calendar#17]
不确定是不是bug，总之切换笔记本后，日历组件就会自动消失，必须要再次点击顶栏打开日历才行

![image](https://github.com/svchord/siyuan-arco-calendar/assets/27268127/c68a8a43-d816-4acf-a7c1-6536f3c72e8e)

**Comment by svchord** [comment]
这个我看不出来是什么问题…只能猜测是点击那个下拉菜单时，被思源识别成点击菜单以外的区域，然后就自动隐藏了，等之后换成边栏dock可能会好点

**Comment by svchord** [comment]
放到边栏dock上了，问题解决
