### ISSUE TITLE
请问思源集市会更新1.0.10版本吗？

### ISSUE THREAD

**Issue by isyngo** [svchord/siyuan-arco-calendar#18]
RT

如果不更新，请问有替代的安装方式吗？

**Comment by svchord** [comment]
集市不是正常更新了吗？请问你的思源版本是不是最新的

**Comment by isyngo** [comment]
已检查，是思源的问题。已下载选项卡不提示更新状态，需要去插件选项卡查看。

**Comment by 88250** [comment]
下个版本修复，感谢反馈 https://github.com/siyuan-note/siyuan/issues/9074
