### ISSUE TITLE
请问如何修改字体？

### ISSUE THREAD

**Issue by isyngo** [svchord/siyuan-arco-calendar#2]
你好，使用插件后，除文档内容的字体外，其他部分（文档树、标签页等）的字体都有变化，因为显示器的问题，需要维持自带主题的原字体，请问需要如何操作？感谢！

操作系统：win10
软件版本：2.7.10
插件版本：0.0.5

对比截图，第一张未使用插件，第二张使用插件。

![image](https://user-images.githubusercontent.com/8169006/226267568-649a920d-1860-47c5-99a7-07bf74c5c3b8.png)

![image](https://user-images.githubusercontent.com/8169006/226267593-bdd4d40d-b3d7-4c5f-b012-1b52875bd481.png)

**Comment by svchord** [comment]
新版暂时解决了，你可以等插件仓库那边更新，或者直接下载本仓库并复制 calendar 文件夹到插件目录
