### ISSUE TITLE
Linux系统下模板路径出错

### ISSUE THREAD

**Issue by sleidga** [svchord/siyuan-arco-calendar#20]
Linux系统（deepin）内新建日记时提示找不到模板文件。用系统的alt+5新建当天日记正常。不知道是不是Linux中路径分隔符不一样导致的。是否能像改主题类似的操作，加入命令将路径调整过来？

![截图_20230923](https://github.com/svchord/siyuan-arco-calendar/assets/145816274/f9806754-9fdc-4d2f-ad2c-6f916ea7938d)

**Comment by sleidga** [comment]
似乎在Linux下，点击不同日期切换日记也无法操作。点击后没有日记出来也没有错误提示。 不知道是不是也是因为路径符号的问题。

**Comment by HowcanoeWang** [comment]
> 似乎在Linux下，点击不同日期切换日记也无法操作。点击后没有日记出来也没有错误提示。 不知道是不是也是因为路径符号的问题。

\+ 1
