### ISSUE TITLE
希望能在日历面板中添加跳转到月份页面的链接

### ISSUE THREAD

**Issue by BopSun** [svchord/siyuan-arco-calendar#21]
实际应用场景是，点击日历面板上的“月份”后能直接跳转到对应月份的页面。我可以在这里写月度总结，并利用[文档流插件](https://github.com/frostime/sy-docs-flow) 生成当月日记的文档流便于整理和查看。

同理，如果点击年份也能做类似的事情，那么过生成的文档流就是月份页面的汇总。

谢谢！

**Comment by svchord** [comment]
我想了下，感觉无法通过笔记本配置的日记新建存放路径判断出月份是哪个文档，月份文档也没有对应的唯一文档属性，所以目前是无法实现的，你可以试试通过面包屑插件之类的方式快速跳转
