### ISSUE TITLE
适配思源添加的 daily note 默认属性

### ISSUE THREAD

**Issue by XinLi0111** [svchord/siyuan-arco-calendar#24]
https://github.com/siyuan-note/siyuan/issues/9807

我按照新的功能自己修改了日记的标题后，所有日记无法在日历面板中被识别了。
请问可以适配新的 dailynote 属性吗

**Comment by svchord** [comment]
感谢f佬的pr，已适配

**Comment by svchord** [comment]
好像还是不太行，我再看看怎么改吧

**Comment by svchord** [comment]
已适配
