### ISSUE TITLE
能否存储日记检索记录

### ISSUE THREAD

**Issue by Achuan-2** [svchord/siyuan-arco-calendar#26]
关闭日历后，再打开又需要重新加载，等待时间有点长
如果能自动存储检索记录就好了
可以加一个刷新按钮，如果更改后，数据和存储的不一样，可以刷新

**Comment by svchord** [comment]
现在可以存储了

**Comment by svchord** [comment]
这个修改导致了当前月份的日记标记不会及时更新，要翻页两下回来才能触发更新，我之后研究一下怎么改

**Comment by Achuan-2** [comment]
只要新建日记日记标记会更新就符合大部分日常使用场景了吧，不知道能不能检测日记创建事件
或者可以添加一个刷新按钮

**Comment by svchord** [comment]
点击新建会更新，主要是删除日记和快捷键创建日记的时候不会及时更新，之前都是靠刚打开就重新搜索解决的

**Comment by Achuan-2** [comment]
我的意思是用快捷键创建日记有没有办法添加回调，删除日记这个场景很少吧，添加一个刷新按钮就好了
