### ISSUE TITLE
在mac系统里面使用这个插件生成日期会报找不到模板的问题

### ISSUE THREAD

**Issue by yingjialong** [svchord/siyuan-arco-calendar#27]
具体截图信息见附件，应该是没有支持mac系统的路径表示
<img width="782" alt="image" src="https://github.com/svchord/siyuan-arco-calendar/assets/3360040/4db144e1-7ca6-4cf6-9156-f9184a1c6922">
<img width="446" alt="image" src="https://github.com/svchord/siyuan-arco-calendar/assets/3360040/0f4dc2da-6b8c-48ca-adf7-1164afdb33b2">
<img width="1009" alt="image" src="https://github.com/svchord/siyuan-arco-calendar/assets/3360040/1ca57252-f05a-4137-ad26-3f0e42388ad4">

**Comment by HowcanoeWang** [comment]
相关issue：#20 

需要使用re来把所有的路径斜杠进行替换，参考这个：
https://github.com/HowcanoeWang/siyuan-calendar-panel/blob/7139ac1ec7f34a4c2e4877ca14efbdc907a66cf6/js/app.230201.js#L414-L416

**Comment by svchord** [comment]
> 相关issue：#20
> 
> 需要使用re来把所有的路径斜杠进行替换，参考这个： https://github.com/HowcanoeWang/siyuan-calendar-panel/blob/7139ac1ec7f34a4c2e4877ca14efbdc907a66cf6/js/app.230201.js#L414-L416

我目前的代码是已经替换了的：
https://github.com/svchord/siyuan-arco-calendar/blob/d0ca93da133dfbd2f09acfc4f77687555b435a9f/src/components/CalendarView.vue#L46

试了下好像直接用，不替换才是在win和mac都能用的

**Comment by svchord** [comment]
我先发一版试试看

**Comment by HowcanoeWang** [comment]
最新版不报错了，在linux上表现正常，能创建带模板的日记；
但在mac上，没有生成模板，只创建了一个空白的日记页面

**Comment by HowcanoeWang** [comment]
> > 相关issue：#20
> > 需要使用re来把所有的路径斜杠进行替换，参考这个： https://github.com/HowcanoeWang/siyuan-calendar-panel/blob/7139ac1ec7f34a4c2e4877ca14efbdc907a66cf6/js/app.230201.js#L414-L416
> 
> 我目前的代码是已经替换了的：
> 
> https://github.com/svchord/siyuan-arco-calendar/blob/d0ca93da133dfbd2f09acfc4f77687555b435a9f/src/components/CalendarView.vue#L46
> 
> 试了下好像直接用，不替换才是在win和mac都能用的

一个猜想，是不是替换反了。。。

```
dailyNoteTemplatePath.replaceAll('\\', '/'); 
```

参考：
```
> siyuan.config.system.appDir
'/home/hwang/Applications/siyuan/resources'
```

应该是把下图中的所有`\`都换成`/`

![](https://private-user-images.githubusercontent.com/3360040/294810302-0f4dc2da-6b8c-48ca-adf7-1164afdb33b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDYwNDcsIm5iZiI6MTcwNDk0NTc0NywicGF0aCI6Ii8zMzYwMDQwLzI5NDgxMDMwMi0wZjRkYzJkYS02YjhjLTQ4Y2EtYWRmNy0xMTY0YWZkYjMzYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDQwMjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUwYzYyNzIyOGEzNzkyMmYyOTk5YmM2YzFmYzMwNGYwMDkyYTllYzQ1Y2FjNjVhYTIzNmUxMjhiMzgzOTQyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OqmQFnJRRhw55mauzP0XLhAG_uM4bU5CJbHL9MhZbds)

**Comment by svchord** [comment]
![image](https://github.com/svchord/siyuan-arco-calendar/assets/61345763/76343159-31c2-4f61-98f5-bd075e608602)


后面这部分是我之前替换了的，前面那部分是接口返回的路径，感觉是替换了才出问题的，所以我才觉得应该保持不变。

而且，没有路径报错也是一个佐证了。

目前的空白文档问题，会不会是先打开页面再调渲染接口的问题，我调换一下顺序，再发一版你试试。

**Comment by HowcanoeWang** [comment]
更新之后可以了，感谢！
