### ISSUE TITLE
是否可以增加顶栏、侧栏位置的设置项

### ISSUE THREAD

**Issue by TopProgrammer** [svchord/siyuan-arco-calendar#28]
是否可以增加顶栏、侧栏位置的设置项，比如顶栏、顶栏左、顶栏右、左侧上、左侧下、右侧上、右侧下。底部左、底部右等。

**Comment by svchord** [comment]
新版直接放在侧栏了，你试试看

**Comment by QMike0** [comment]
> 新版直接放在侧栏了，你试试看

佬，可以同时支持放在顶栏吗，已经习惯在顶栏了，放在侧栏打开后需要缩进编辑器区域，很不适应...

**Comment by svchord** [comment]
我之后看看怎么配置吧

**Comment by QMike0** [comment]
> 我之后看看怎么配置吧

好的，谢谢佬

**Comment by netdog2019** [comment]
一直在顶栏，换到侧栏了，真不习惯，可以多给个在顶栏的选项吗？

**Comment by liao-zh** [comment]
给个选项+1，能自己选择在顶栏左/右或者侧栏，应该可以解决问题了hh

**Comment by gdy106** [comment]
习惯在顶栏了，改成侧栏很不适应。实际体验感觉更不方便了。希望能够提供顶栏的选项。

**Comment by svchord** [comment]
已更新
