### ISSUE TITLE
v1.4.3 bug：点击已高亮的日期时未打开相应的日记

### ISSUE THREAD

**Issue by liao-zh** [svchord/siyuan-arco-calendar#29]
如录屏所示，点击一个日期，日记打开，关闭这个日记，再点击这个日期时，日记未能打开。

https://github.com/svchord/siyuan-arco-calendar/assets/27865589/3dcadefc-9641-4c02-9d02-2afba9293dc7

**Comment by Achuan-2** [comment]
加1，已高亮的日期无法再点击触发打开笔记

**Comment by Achuan-2** [comment]
建议改进下，举例常见场景：点击日历打开了一个日记，然后切换到另一个笔记，如果再想打开该日记，就无法直接通过点击日历的对应打开，只能点击其他日期再点击该日期

**Comment by svchord** [comment]
收到，晚上下班回去就修复

**Comment by svchord** [comment]
发现这个和底部的今天按钮冲突了，只能先取消今天按钮的功能了

**Comment by Achuan-2** [comment]
> 发现这个和底部的今天按钮冲突了，只能先取消今天按钮的功能了

？？？好像没觉得冲突呀

**Comment by svchord** [comment]
底部今天按钮的逻辑实现是靠选中日期变化实现的，点击已高亮（即已选中）的日期不会触发日期变化回调，如果两个逻辑并存就会打开两次，我准备重新写一个底部的今天按钮，这样就能规避了
