### ISSUE TITLE
i18n: Missing Translation

### ISSUE THREAD

**Issue by candideu** [svchord/siyuan-arco-calendar#30]
Hello! Thank you for creating this plugin, and creating an English version!

I just wanted to note an untranslated string in the window, which doesn't seem to be present in the [i18n files](https://github.com/svchord/siyuan-arco-calendar/tree/main/public/i18n).

![image](https://github.com/svchord/siyuan-arco-calendar/assets/55474996/71669b3f-ed50-42e6-859a-a01b4fbb1d69)

**Comment by svchord** [comment]
Thanks, this problem will be fixed in the next version.
