### ISSUE TITLE
点击日期无法自动新建日记，只能新建文档

### ISSUE THREAD

**Issue by QMike0** [svchord/siyuan-arco-calendar#33]
思源：v3.0.10，插件为最新版

现在点击日历插件中的日期后无法按照路径新建日记，而是在选择的笔记本中生成标题为`.`的新文档，该文档的自定义属性为"custom-dailynote-20240418: 20240418"（以2024.4.18为例）
![image](https://github.com/svchord/siyuan-arco-calendar/assets/43239563/db2940c0-93ee-46a5-acc2-7c2d9ba9030b)
![image](https://github.com/svchord/siyuan-arco-calendar/assets/43239563/f639e773-3ae1-430f-8e37-995ac8f7f232)

**Comment by svchord** [comment]
能不能给一下你的日历路径模板？

**Comment by QMike0** [comment]
不好意思，才发现不知道啥时候改了dailynote文件夹路径，笔记本里面没设置日历路径o.0
