### ISSUE TITLE
请问如何自动退出日历面板？

### ISSUE THREAD

**Issue by isyngo** [svchord/siyuan-arco-calendar#4]
你好，目前进行日期的点选后，日历面板会默认保留，需要点击空白处退出。请问如何在点选日期后自动退出面板呢？谢谢~

操作系统：win10
软件版本：2.8.0
插件版本：0.0.6

**Comment by svchord** [comment]
抱歉，我目前没能想出怎么实现这个功能

**Comment by isyngo** [comment]
好的，谢谢
