### ISSUE TITLE
对于新建日记路径非默认的认不出已有日记

### ISSUE THREAD

**Issue by hscui** [svchord/siyuan-arco-calendar#5]
我的新建日记路径是修改过的：
![图片](https://user-images.githubusercontent.com/7949195/227416341-7fd22dbe-c8cb-489e-a41d-81d74209d758.png)
所以安装这个插件后，点击日历不会跳转到已有日记，而是按日历日期新增一条日历，名字最后以星期日结尾
![图片](https://user-images.githubusercontent.com/7949195/227416419-e7bc5bb9-34e7-4edd-b1fd-64d82fd8df2f.png)

**Comment by svchord** [comment]
我向思源提了路径解析接口的需求，要先等那边搞定了才能改

**Comment by svchord** [comment]
新版已解决
