### ISSUE TITLE
已有日记不现实的问题

### ISSUE THREAD

**Issue by WolkeAtreide** [svchord/siyuan-arco-calendar#8]
如图，貌似只识别出了2、3、4号的日记，其他日期的日记没有识别成功，但是能够正常打开。
![image](https://github.com/svchord/siyuan-arco-calendar/assets/101959415/83c230bc-b43e-40f5-bdd2-05fa627f8952)
![image](https://github.com/svchord/siyuan-arco-calendar/assets/101959415/8b066a83-c428-40eb-a5c8-cff5b91d94bf)

**Comment by svchord** [comment]
现在更新到了官方插件集市，你可以看看还有没有这个问题，或者你是不是没有用默认的日记存储路径

**Comment by HowcanoeWang** [comment]
> 现在更新到了官方插件集市，你可以看看还有没有这个问题，或者你是不是没有用默认的日记存储路径

不支持自定义日记路径吗？我这边一直报错

![image](https://github.com/svchord/siyuan-arco-calendar/assets/19968935/4e0cfe00-9e8b-4c7f-97a7-a7c88e7e409c)

**Comment by svchord** [comment]
目前是不支持自定义路径的，但这个报错应该不是这个问题，你的思源版本是2.8.10以上吗？

**Comment by HowcanoeWang** [comment]
> 目前是不支持自定义路径的，但这个报错应该不是这个问题，你的思源版本是2.8.10以上吗？

最新的2.9.0，安装插件后重启思源好了，但是由于不支持自定义日记模板，所以完全没法用，当时我修那个js源码的最大一个点就是因为这个😂

https://github.com/HowcanoeWang/siyuan-calendar-panel/blob/7139ac1ec7f34a4c2e4877ca14efbdc907a66cf6/js/app.230201.js#LL376C17-L436C19

ts代码完全不会改，看看上面的有没有参考价值

**Comment by svchord** [comment]
目前普通的2006、01、02是支持的，我当时就是参考了大佬你这个然后优化了一点的，只是不支持星期几那种很复杂的sprig语法。

https://github.com/svchord/siyuan-arco-calendar/blob/ff07de6d28138a2ebde35f050ae877cac840fc79/src/components/CalendarView.vue#LL57C1-L85C2

另外，现在后端也给了渲染模板变量的接口，不过因为异步的问题我一直没整好…之后可能会通过往日记文档添加自定义属性来实现

**Comment by HowcanoeWang** [comment]
> 

可以测试一下我这样的（年/年月/年月日）：

```
/今日速记/{{now | date "2006/2006.01"}}/{{now | date "2006.01.02"}}
```

至少目前还不支持

![image](https://github.com/svchord/siyuan-arco-calendar/assets/19968935/2c89a686-389b-4f28-8bc0-3a3f86551730)

大体思路是，从上面的这个模板string，替换成对应的年月日`e[0], e[1], e[2]`, 然后e就带入当天/用户点击的日期，来获取最终的日记文件路径；看你目前的代码，好像是假设年月日只会在模板string里出现一次

**Comment by svchord** [comment]
思源2.8.10是没问题的
![image](https://github.com/svchord/siyuan-arco-calendar/assets/61345763/7741e6d4-3536-48d1-8fc4-943632c8858e)

~~应该是2.9.0更新了什么导致的冲突。~~

不对，我更新到2.9仍然没有问题啊，和上图一样

> 看你目前的代码，好像是假设年月日只会在模板string里出现一次

不是的，我就是为了适配出现多次，才做的递归处理

**Comment by svchord** [comment]
![image](https://github.com/svchord/siyuan-arco-calendar/assets/61345763/c7cf316f-e45a-4137-bbb5-c7ff15157233)

群里的大佬找到了问题所在了，我看看怎么解决

**Comment by HowcanoeWang** [comment]
> ![image](https://github.com/svchord/siyuan-arco-calendar/assets/61345763/c7cf316f-e45a-4137-bbb5-c7ff15157233)
> 
> 群里的大佬找到了问题所在了，我看看怎么解决

我印象里，我的代码是一个月一个月查的，不是一次查询所有然后再过滤

https://github.com/HowcanoeWang/siyuan-calendar-panel/blob/calendar-v7-fix/js/app.230201.js#L502-L530

**Comment by svchord** [comment]
新版已解决
