### ISSUE TITLE
请问有上线思源集市的计划吗？

### ISSUE THREAD

**Issue by isyngo** [svchord/siyuan-arco-calendar#9]
请问有上线思源集市的计划吗？如果没有，请问是否有替代安装的方法呢？一直期待能继续使用中，谢谢~

**Comment by svchord** [comment]
在迁移了，因为想改的地方比较多，加上本职工作最近比较忙，所以才慢了点。如果很急的话，我就先把之前的版本发到集市上了

**Comment by isyngo** [comment]
好的，非常感谢，等待新版本的发布
